; Generated by the BASIQuinho compiler
; BASIQuinho Compiler: https://github.com/edwilsonferreira/BASIQuinho
; Generated on: 28/04/2026 at 11:18
;
; To compile this LLVM IR code to an executable:
; 1. Ensure you have Clang installed (or an equivalent LLVM toolchain).
; 2. Run the command:
;    clang your_output_filename.ll -o your_executable_name
;
; Alternatively, using llc (LLVM static compiler) and a C linker (e.g., gcc or clang):
; 1. Generate an object file from LLVM IR:
;    llc -filetype=obj your_output_filename.ll -o your_output_filename.o
; 2. Link the object file to create an executable:
;    clang your_output_filename.o -o your_executable_name
;    (or use gcc: gcc your_output_filename.o -o your_executable_name)
;

target triple = "x86_64-pc-linux-gnu" ; Ajuste conforme sua plataforma alvo

; Declaracoes de funcoes C externas para I/O
@.str.print.num.fmt = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.str.print.str.fmt = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.scan.num.fmt = private unnamed_addr constant [3 x i8] c"%d\00"
declare i32 @printf(i8* nocapture readonly, ...) nounwind
declare i32 @scanf(i8* nocapture readonly, ...) nounwind

@.str.const.0 = private unnamed_addr constant [12 x i8] c"Olá Mundo!\00"
@.str.const.1 = private unnamed_addr constant [13 x i8] c"Tchau Mundo!\00"

define i32 @main() {
entry:
  %ptr.x = alloca i32, align 4 ; Var x (tipo i32)
  ; TAC: x := 1
  store i32 1, i32* %ptr.x, align 4
  ; TAC: t0 := x == 1
  %r0 = load i32, i32* %ptr.x____1, align 4
  %t0 = add i32 %r0, 0 ; Assign i32 to temp t0
  %r1 = icmp eq i32 %t0, 0
  br i1 %r1, label %L0, label %NEXT_L0
  ; TAC: PRINT "Olá Mundo!"
  %r2 = getelementptr inbounds [12 x i8], [12 x i8]* @.str.const.0, i64 0, i64 0
  %r3 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str.print.str.fmt, i64 0, i64 0), i8* %r2)
  br label %L1
L0:
NEXT_L0:
  ; TAC: PRINT "Tchau Mundo!"
  %r4 = getelementptr inbounds [13 x i8], [13 x i8]* @.str.const.1, i64 0, i64 0
  %r5 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str.print.str.fmt, i64 0, i64 0), i8* %r4)
L1:
NEXT_L1:
  ret i32 0
}
